import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { normalizeChapter, validateChapter } from "../src/content/schema.js";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHAPTERS_DIR = path.join(ROOT_DIR, "content", "chapters");
const DRAFTS_DIR = path.join(ROOT_DIR, "content", "drafts", "nndl");
const OUTPUT_FILE = path.join(ROOT_DIR, "src", "generated", "book-content.generated.js");

async function readChapterDirectories() {
  const entries = await readdir(CHAPTERS_DIR, { withFileTypes: true });
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort();
}

async function readDraftChapters() {
  try {
    const entries = await readdir(DRAFTS_DIR, { withFileTypes: true });
    const drafts = [];

    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith(".json")) {
        continue;
      }
      const payload = JSON.parse(await readFile(path.join(DRAFTS_DIR, entry.name), "utf8"));
      drafts.push(payload);
    }

    return drafts;
  } catch (error) {
    if (error?.code === "ENOENT") {
      return [];
    }
    throw error;
  }
}

async function readBaseChapters() {
  const chapterIds = await readChapterDirectories();
  const chapters = [];

  for (const chapterId of chapterIds) {
    const chapterPath = path.join(CHAPTERS_DIR, chapterId, "chapter.json");
    const payload = JSON.parse(await readFile(chapterPath, "utf8"));
    chapters.push(payload);
  }

  return chapters;
}

async function readChapters() {
  const baseChapters = await readBaseChapters();
  const draftChapters = await readDraftChapters();
  const chapterMap = new Map(baseChapters.map((chapter) => [chapter.id, chapter]));

  draftChapters.forEach((draft) => {
    chapterMap.set(draft.id, draft);
  });

  return [...chapterMap.values()]
    .map((chapter, index) => normalizeChapter(chapter, index))
    .sort((left, right) => left.order - right.order);
}

function assertValid(chapters) {
  const errors = chapters.flatMap((chapter) => validateChapter(chapter));
  const chapterIds = new Set();
  chapters.forEach((chapter) => {
    if (chapterIds.has(chapter.id)) {
      errors.push(`duplicate chapter id ${chapter.id}`);
    }
    chapterIds.add(chapter.id);
  });

  if (errors.length) {
    throw new Error(`Content validation failed:\n- ${errors.join("\n- ")}`);
  }
}

function toModuleSource(chapters) {
  return `// This file is generated by scripts/build-content.js\nexport const BOOK_CHAPTERS = ${JSON.stringify(chapters, null, 2)};\n`;
}

async function main() {
  const chapters = await readChapters();
  assertValid(chapters);
  await writeFile(OUTPUT_FILE, toModuleSource(chapters), "utf8");
  console.log(`Built ${chapters.length} chapters -> ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
